/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhe_localadd_MainActivity */

#ifndef _Included_com_xiaozhe_localadd_MainActivity
#define _Included_com_xiaozhe_localadd_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozhe_localadd_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaozhe_localadd_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
