/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhe_ndkpath_MainActivity */

#ifndef _Included_com_xiaozhe_ndkpath_MainActivity
#define _Included_com_xiaozhe_ndkpath_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozhe_ndkpath_MainActivity
 * Method:    helloC
 * Signature: ()Ljava/lang/String;
 */

//JNIEXPORT jstring JNICALL Java_com_xiaozhe_ndkpath_MainActivity_helloC
//  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
