/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhe_logfromc_MainActivity */

#ifndef _Included_com_xiaozhe_logfromc_MainActivity
#define _Included_com_xiaozhe_logfromc_MainActivity
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
#endif
