/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhe_fork_MainActivity */

#ifndef _Included_com_xiaozhe_fork_MainActivity
#define _Included_com_xiaozhe_fork_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozhe_fork_MainActivity
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaozhe_fork_MainActivity_logout
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
