/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhe_passencode_MainActivity */

#ifndef _Included_com_xiaozhe_passencode_MainActivity
#define _Included_com_xiaozhe_passencode_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozhe_passencode_MainActivity
 * Method:    passencode
 * Signature: (I)I
 */


#ifdef __cplusplus
}
#endif
#endif
